### ISSUE TITLE
Set membership

### ISSUE THREAD

**Issue by zickau** [ing-bank/zkrp#2]
Hi

How can I use your code to setup and verify a set membership zkp?

Best
Sebastian

**Comment by mvdbos** [comment]
Please have a look at this unit test: https://github.com/ing-bank/zkrp/blob/master/ccs08/ccs08_test.go#L127

It proves and verifies that `12` is part of the set `[12, 42, 61, 71]`.

Can you close the issue if this helps you out?

**Comment by zickau** [comment]
That's great. thx a lot.
